### ISSUE TITLE
Integrate external Particle System Simulator

### ISSUE THREAD

**Issue by jellepoland** [awegroup/ASKITE#54]
### General
- [x] Test the import, statement, and include into the pyproject.toml. Only works for importing .py files, which means the test cases won't just work. Trying to solve this in  #55
- [x] Make an implementation plan

# Implementation
- [x] 1. Change remote name, and author names, and other .toml items, to a package name that you would like to call, e.g. Particle_System_Simulator (preferably ParticleSystemModel), but can always be called like import Particle_System_Simulator as PSM. 

    To change the package name, you'll need to modify the name field under the [project] section, inside the .toml. Update description, update keywords.  Updated the repository URL to match the actual repository you're using, should also point to main rather than develop to always only take a stable release.

    After making these changes to the ParticleSystemSimulator's pyproject.toml file, you'll need to rebuild and reinstall that package. Then, update your kitesim pyproject.toml file to use the new name.

- [x] 2. Identify working files in Particle_System_Simulator, that can be used to relearn the code:
- code_Validation/saddel_form
- Simulations/Gao_et_al.py
- Tutorial1 (not Tutorial2 and not Poisson's ratio)

- [x] 3. Check how you currently feed Alex's his code, and make notes
### Instantiating
```
psystem = ParticleSystem(
        input_PSM["connectivity_matrix"], # np.array (94,2)
        input_PSM["initial_conditions"], #list len 37
        input_PSM["params_dict"], # dict len 16
    )
```
A dataframe is created to store the positions and time vector:
```
    t_vector = np.linspace(
        params["dt"], params["t_steps"] * params["dt"], params["t_steps"]
    )
    x = {}
    for i in range(params["n"]):
        x[f"x{i + 1}"] = np.zeros(len(t_vector))
        x[f"y{i + 1}"] = np.zeros(len(t_vector))
        x[f"z{i + 1}"] = np.zeros(len(t_vector))
    position = pd.DataFrame(index=t_vector, columns=x)
    aero_structural_tol = params["aerostructural_tol"]
```

### Solving
Feed in external force: `position.loc[step], _ = psystem.kin_damp_sim(f_external)`
Extracting different point format for aero (might become redundant): `points = psystem.x_current_2D`
Extracting the internal forces, used to compute residual forces by removing first link's force: `f_internal = psystem.f_int`
Extracting and updating rest-lengths: `psystem.extract_rest_length[index_depower_tape] - initial_length_depower_tape)` & `psystem.update_rest_length(index_steering_tape_left, steering_tape_extension_step)`

- [x] 4. Compare this with the WORKING files and list what should be changed

### Initialisation changes that must be resolved
- [x] connections, are structured differently, see Tutorial 1 for how they are newly defined. Old was to just have `[[index point 1, index point 2], ... ]
- [x] initial conditions are still structured in precisely the same fashion (see Tutorial 1, which describes it well)
- [x] params  have similar items, however Mark's code can not handle stiffness to be defined per link and pulley other line pair also not. My params misses the entries "g"

### Simulation changes that must be resolved
- [x] f_external shape is already flat, so that works well.
- [x] output of kin_damp_sim remains the same
- [x] x_current_2D function is NOT present in Mark, and taken out, instead it is computed inside the solver_main code

## Implementation Plan
**Initialisation**
- [x] Restructure connections by adding the stiffness and damping parameter to each row entry. (See Tutorial 1, for an explanation of the right input)
- [x] Figure out how is_tension/is_compression/is_pulley should be handled in Mark's code
- [x] Inside ParticleSystem, allow dealing with the occurrence of pulleys.
- [x] Mark handles these through a base class, that specifies the linktype. Add the new types: "pulley" and "default"
- [x] Also adjust Mark's SpringDamper code to handle the pulley type, once specified
- [x] Add pulley other line pair to Mark's code
- [x] feeding dt into the SpringDamper class is obsolete, so leave it out.
- [x] Add "g" to the params dict using the .update function
- [x] Verify the workings of the initialisation

**Simulation**
- [x] In Mark's code, the rest-length are calculated based on the relative position, instead of fed to the system. You will need to add a function to add to this initial rest-length, such that you can simulate KCU actuation.
- [x] Mark directly puts the nodes that are fixed to zero, instead of doing this within the script. You could add another function that returns the forces without substracting the zero one. Make a new property and call it def f_all.
- [x] update rest length and extract rest-lengths are not present in Mark's code and must be added, can use kitesim's particle system version and just copy paste the new methods in.
- [x] Verify workings

## Writing a kite_tutorial
- [x] fix input to take the enum
- [x] write tutorial in psm repo
- [x] copy-paste and make working in kitesim

# Finalizing
- [x] Mark does a time loop untill Ekin of structural solver is converged, while we are updating aerodynamics each round, perhaps we could also get away with doing an aerodynamic update every 10 steps or so.
- [x] Mark uses an `np.max(Ekin[-10,-1])` as a convergence criteria which I quite like
- [x] Add Tutorial 1 --from Particle_System_Simulator-- which nicely describes the data-structure, to the examples folder in kitesim
- [ ] Cleaning up files
